### ISSUE TITLE
Current Development

### ISSUE THREAD

**Issue by ghost** [sglvladi/MATLAB#1]
sglvladi, I'm working on a filter for my FMCW radar for airplane collision avoidance.  I had been reading about multiple object tracking, some european researchers had done work on 'multiple extended object tracking' [https://www.researchgate.net/profile/Paolo_Braca/publication/305303221_Converted_Measurements_Bayesian_Extended_Target_Tracking_Applied_to_X-band_Marine_Radar_Data/links/5787541608aea50b6b18e87d/Converted-Measurements-Bayesian-Extended-Target-Tracking-Applied-to-X-band-Marine-Radar-Data.pdf](url).   I found what I assume is your post on Mathworks File Exchange (it's referenced as 'backup code' in some of these files).  all of this work stems from the 2009 Bar-Shalom paper.  I looked around and got to this github repo.  you have a lot of great work here.  are you still developing this stuff?  
I write in python, and I based my writeup of the Bar-Shalom paper on that exchange file, but in python.  Here is a screen shot with one track shown as an airplane (it is all generated data, but i have real sensor data that i'm working on right now).
![image](https://user-images.githubusercontent.com/32305856/34342895-aad5d05e-e973-11e7-9404-6dcfbe129847.png)

If you're willing, i'd like to have an email chat, or voip call or something to ask you about your work and experience in this area.  We can set up private correspondence if you respond.  I look forward to it.  
Darren

**Comment by sglvladi** [comment]
Hi Darren,

Thanks for your interest and I am glad that some of my work can potentially be useful to someone else. I am indeed still developing the code, as I still have around 1.5 years left in my PhD. 

I am not sure to which Mathworks Exchange File you are referring (I can't remember publishing anything on Mathworks), but I hope it is actually my work, as the "MATLAB" repository is simply my initial MATLAB workspace folder which, among other things, does contain work done by other people (for which of course I am not claiming ownership). I would advise you to have a look at another one of my repositories, named "TrackingX" (see here: https://github.com/sglvladi/TrackingX), where I have gathered all the work I have done on Target Tracking with the aim of developing unified object oriented target tracking framework for MATLAB (work in progress).

My interests also evolve around multi-target, X-band radar tracking, although my application domain is mostly maritime rather than airborne, but I would be more than happy to lend you a hand if it is within my abilities. Continuing, I have not looked a great deal at extended target tracking (so far), but it does fall under my research interests and I have been experimenting extensively with track initiation and data association algorithms.

I am currently away on holidays and will be back in office around 15th Jan, but feel free to contact me at any time and I'll respond promptly. My academic email is: sglvladi@liverpool.ac.uk, which would be a better point of contact for this kind of correspondence.

Looking forward to hearing from you.

Best,
Lyudmil

P.S. Please ping me an email once you have seen this.

**Comment by sglvladi** [comment]
Hi Darren,

Thanks for your interest and I am glad that some of my work can potentially be useful to someone else. I am indeed still developing the code, as I still have around 1.5 years left in my PhD. 

I am not sure to which Mathworks Exchange File you are referring (I can't remember publishing anything on Mathworks), but I hope it is actually my work, as the "MATLAB" repository is simply my initial MATLAB workspace folder which, among other things, does contain work done by other people (for which of course I am not claiming ownership). I would advise you to have a look at another one of my repositories, named "TrackingX" (see here: https://github.com/sglvladi/TrackingX), where I have gathered all the work I have done on Target Tracking with the aim of developing unified object oriented target tracking framework for MATLAB (work in progress).

My interests also evolve around multi-target, X-band radar tracking, although my application domain is mostly maritime rather than airborne, but I would be more than happy to lend you a hand if it is within my abilities. Continuing, I have not looked a great deal at extended target tracking (so far), but it does fall under my research interests and I have been experimenting extensively with track initiation and data association algorithms.

I am currently away on holidays and will be back in office around 15th Jan, but feel free to contact me at any time and I'll respond promptly. My academic email is: sglvladi@liverpool.ac.uk, which would be a better point of contact for this kind of correspondence.

Looking forward to hearing from you.

Best,
Lyudmil

P.S. Please ping me an email once you have seen this.
